title: Halil Kolatan
position: M.Sc. Student
affiliation: Ankara University
email: halilkolatan@pm.me
keywords: minimal academic
#google_scholar: https://scholar.google.com/
github_link: https://github.com/yaoyao-liu/minimal-light
linkedin: https://www.linkedin.com/
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/science1.png
favicon_dark: ./assets/img/science1.png
description: personal homepage
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
